config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

	root"users#index"
	resources :users

		get "page-top-secrete", to: "pages#index"

		get    '/login',   to: 'sessions#new'
		post   '/login',   to: 'sessions#create'
		delete '/logout',  to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index

	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      #la ligne qui suit est équivalente à un if
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params_user)
      if @user.save
        remember @user
        flash[:success] = "Votre profil a bien été créé !"
        redirect_to users_path
      else
        render "new"
      end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    # On interdit à un user de modifier le profil d'un autre user    
    if @user == current_user
      render 'edit'
    else 
      flash.now[:error] = "Impossible de modifier un profil qui n'est pas le tien !"
      render 'show'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(params_user)
      redirect_to users_path
    else
      render "new"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private
  def params_user
    params.permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Ma page secrete", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", users_path %></li>
        <li><%= link_to "Help", "#" %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign up", new_user_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Site top secret</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Bienvenu sur la page top secrete!</h1>

  <% if logged_in? %>
  <h1>42!</h1>
  <iframe width="560" height="315" src="https://www.youtube.com/embed/jwEPCn6lRo4?rel=0&amp;controls=0&amp;showinfo=0&amp;start=102&amp;autoplay=1" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

  <% else %>
  <h3>Connecte-toi pour connaître le secret !</h3>
	<%= link_to "Ok, go", login_path, class: "btn btn-lg btn-danger" %> 
  <% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
	<%= label_tag 'name', "Nom de l'utilsateur" %> 
	<%= text_field_tag 'name' %> 

	<%= label_tag 'email', 'Email' %> 
	<%= text_field_tag 'email' %>

	<%= label_tag 'password', 'Mot de passe' %> 
	<%= password_field_tag 'password' %>

app/views/users/edit.html.erb
<h1>Editer l'utilisateur</h1>
<%= form_tag (users_path) do %>   
  <%= render 'form' %>
	<%= submit_tag "Editer l'utilisateur"%> 
<% end %>

app/views/users/index.html.erb
<% if logged_in? %>

<h1> <%= current_user.name %> </h1>

<h2> Bienvenue sur le site qui vous donnera la clé de l'univers. </h2>

<p> Tu souhaites connaître la réponse à la question de l'univers ? </p>

<p> <%= link_to "click ici", page_top_secrete_path, class: "btn btn-success"%> </p>


<% else %>

<h1> Cher visiteur </h1>

<h2> Bienvenue sur le site qui vous donnera la clé de l'univers. </h2>

<p> Tu souhaites connaître la réponse à la question de l'univers ?  </p>

<p> Alors il faudra t'identifier ! </p>

<p> <%= link_to "Log in", login_path, class: "btn btn-success" %> </p>


<% end %>

app/views/users/new.html.erb
<h1>Créer un nouvel utilisateur</h1>

	<%= form_tag (users_path) do %>   
	<%= render 'shared/error_messages' %>
	<%= render 'form' %>
	<%= submit_tag "Créer nouvel utilisateur", class: "btn btn-primary"  %>
<% end %>

app/views/users/show.html.erb
<h1>Profil utilisateur</h1>

<%= @user.name %>
<%= @user.email %>

<%= link_to "Editer l'utilisateur", edit_user_path %>
<%= link_to "Supprimer l'utilisateur", user_path,
			method: :delete,
			data: {confirm: "Are you sure"} %>